---
name: POE-Component-WWW-Google-Calculator
version: 0.02
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  A non-blocking POE wrapper
  around WWW::Google::Calculator
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Filter::Line: 1.192
  POE::Filter::Reference: 1.2187
  POE::Wheel::Run: 1.2179
  WWW::Google::Calculator: 0.04
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::Google::Calculator:
    file: lib/POE/Component/WWW/Google/Calculator.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
